#pragma once
#define CAN_SPI_CS 10
#define CAN_INT_PIN 2
#define WIPER_INPUT1 A5 
#define WIPER_INPUT2 A4
#define FOURWSS_INPUT1 A3
#define FOURWSS_INPUT2 A2
#define HAZARD_INPUT A1
#define HEADLIGHT_INPUT A0
//#define RADIO_INPUT
#define BRAKE_INPUT 3
#define LSIG_INPUT 9
#define RSIG_INPUT 5
#define REGEN_INPUT 8
#define SHUTDOWNPI_INPUT 7
#define LAPCOUNTER_INPUT 6
#define STATUSLED_OUTPUT 4 // NC yet
